package com.posse.kotlin1.calendar.app_theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB72300)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD3)
val md_theme_light_onPrimaryContainer = Color(0xFF3D0600)
val md_theme_light_secondary = Color(0xFF376A20)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB7F397)
val md_theme_light_onSecondaryContainer = Color(0xFF062100)
val md_theme_light_tertiary = Color(0xFF825500)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB3)
val md_theme_light_onTertiaryContainer = Color(0xFF291800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF3F001C)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF3F001C)
val md_theme_light_surfaceVariant = Color(0xFFF5DDD8)
val md_theme_light_onSurfaceVariant = Color(0xFF534340)
val md_theme_light_outline = Color(0xFF85736F)
val md_theme_light_inverseOnSurface = Color(0xFFFFECEF)
val md_theme_light_inverseSurface = Color(0xFF5E1130)
val md_theme_light_inversePrimary = Color(0xFFFFB4A4)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB72300)

val md_theme_dark_primary = Color(0xFFFFB4A4)
val md_theme_dark_onPrimary = Color(0xFF630E00)
val md_theme_dark_primaryContainer = Color(0xFF8C1800)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD3)
val md_theme_dark_secondary = Color(0xFF9CD67E)
val md_theme_dark_onSecondary = Color(0xFF103900)
val md_theme_dark_secondaryContainer = Color(0xFF1F5107)
val md_theme_dark_onSecondaryContainer = Color(0xFFB7F397)
val md_theme_dark_tertiary = Color(0xFFFFB951)
val md_theme_dark_onTertiary = Color(0xFF452B00)
val md_theme_dark_tertiaryContainer = Color(0xFF633F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF3F001C)
val md_theme_dark_onBackground = Color(0xFFFFD9E1)
val md_theme_dark_surface = Color(0xFF3F001C)
val md_theme_dark_onSurface = Color(0xFFFFD9E1)
val md_theme_dark_surfaceVariant = Color(0xFF534340)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BD)
val md_theme_dark_outline = Color(0xFFA08C88)
val md_theme_dark_inverseOnSurface = Color(0xFF3F001C)
val md_theme_dark_inverseSurface = Color(0xFFFFD9E1)
val md_theme_dark_inversePrimary = Color(0xFFB72300)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB4A4)


val seed = Color(0xFFFB3300)
